### PR TITLE
Fix links to docs

### LINKED ISSUE #1: All docs links in the /src directory are 404s
In the file `src\Mux.Csharp.sdk\README.md` all the links for docs `404` as they are assuming the file is in the route of the project.

### PR DESCRIPTION
**Pull request by baynezy**
In the README all the links were pointing at the wrong location
so when you tried to view them on GitHub they resulted in a 404.

Fixes #1

### CODE REVIEW

**Comment by baynezy** [comment]
@eropple - is this an acceptable PR?

**Comment by eropple** [comment]
I don't work at Mux anymore, sorry. cc @jaredsmith

**Comment by baynezy** [comment]
@jaredsmith - is this a acceptable PR? Or is this repo abandoned?

**Comment by jaredsmith** [comment]
No, this repo is not abandoned.  I've just been a bit busy this week, and it's taken me longer than expected to respond.

The short answer is that the PR isn't quite correct -- the README.md file gets auto-generated from the mustache template in `gen/templates/README.mustache`, so any changes made directly to the README.md file would get overwritten the next time we regenerated the code (and, by extension, the README.md file).  The proper way to fix this would to fix it in the `gen/templates/README.mustache` file.  I'll try to get to that before the end of the week.

**Comment by baynezy** [comment]
Thanks @jaredsmith I am happy to do the work if you point me in the right direction. I assume the `apiDocPath` needs amending, but I am not sure that is present in the repository.

**Comment by baynezy** [comment]
Closing as it doesn't seem like a priority.

**Pull request closed without merging**
